apiVersion: v1
kind: Secret
metadata:
  name:  mongodb-secrets
data:
  username:  cm9vdA==          #root    # echo -n 'root' | bash64
  password:  cGFzc3dvcmRAMTIz  #password@123  # echo -n 'mypass1234' | bash64
type: Opaque