apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongoexp-dep
spec:
  selector:
    matchLabels:
      app: mongo-erpress
  template:
    metadata:
      labels:
        app: mongo-erpress
    spec:
      containers:
      - name: mongoexp-app
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            secretKeyRef:
              key: database_url
              name: mongoexp-config
